#!/usr/bin/env bash
set -e
 
mkdir -p $HOME/bin
 
# download the BaseSpace CLI
wget "https://launch.basespace.illumina.com/CLI/latest/amd64-linux/bs" -O $HOME/bin/bs
 
chmod u+x $HOME/bin/bs
 
ln -s $HOME/bin/bs /usr/local/bin